# Generated by Django 6.0.2 on 2026-02-12 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaceAcademyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='assignedPAC',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PaceAcademyApp.pacs'),
        ),
    ]
