# Generated by Django 6.0.2 on 2026-02-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaceAcademyApp', '0002_students_assignedpac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacs',
            name='department',
        ),
        migrations.RemoveField(
            model_name='pacs',
            name='name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='department',
        ),
        migrations.RemoveField(
            model_name='students',
            name='name',
        ),
        migrations.AddField(
            model_name='pacs',
            name='firstName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pacs',
            name='surname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='course',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='firstName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='students',
            name='surname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pacs',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
