# Generated by Django 6.0.2 on 2026-02-12 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaceAcademyApp', '0003_remove_pacs_department_remove_pacs_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='assignedPAC',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='PACs', to='PaceAcademyApp.pacs'),
        ),
    ]
