# Generated by Django 6.0.2 on 2026-02-12 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaceAcademyApp', '0004_alter_students_assignedpac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacs',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='pacs',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='id',
        ),
        migrations.AlterField(
            model_name='pacs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='students',
            name='assignedPAC',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='PACs', to='PaceAcademyApp.pacs'),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(default='', max_length=254, primary_key=True, serialize=False),
        ),
    ]
