# Generated by Django 6.0.2 on 2026-02-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaceAcademyApp', '0005_rename_firstname_pacs_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
