# Generated by Django 6.0.2 on 2026-02-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaceAcademyApp', '0006_students_id_alter_students_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
