# Generated by Django 6.0.2 on 2026-02-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaceAcademyApp', '0007_alter_pacs_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacs',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='pacs',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
