# Generated by Django 6.0.2 on 2026-02-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaceAcademyApp', '0008_rename_first_name_pacs_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacs',
            old_name='lastName',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='lastName',
            new_name='surname',
        ),
    ]
