# Generated by Django 6.0.2 on 2026-02-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaceAcademyApp', '0009_rename_lastname_pacs_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
