# Generated by Django 6.0.2 on 2026-02-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaceAcademyApp', '0010_alter_pacs_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacs',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='pacs',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='assignedPAC',
            new_name='assigned_pac',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='surname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
