# Generated by Django 6.0.2 on 2026-02-15 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaceAcademyApp', '0011_rename_firstname_pacs_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacs',
            options={'verbose_name_plural': 'PACs'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='students',
            name='assigned_pac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PACs', to='PaceAcademyApp.pacs'),
        ),
    ]
