# Generated by Django 6.0.2 on 2026-02-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaceAcademyApp', '0012_alter_pacs_options_alter_students_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pacs',
            options={'verbose_name': 'PAC', 'verbose_name_plural': 'PACs'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
