# Generated by Django 6.0.2 on 2026-02-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaceAcademyApp', '0013_alter_pacs_options_alter_students_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pacs',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_pac'),
        ),
        migrations.AddConstraint(
            model_name='students',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_students'),
        ),
    ]
