# Generated by Django 6.0.2 on 2026-02-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaceAcademyApp', '0014_pacs_unique_email_pacs_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pacs',
            name='unique_email_pacs',
        ),
        migrations.RemoveConstraint(
            model_name='students',
            name='unique_email_students',
        ),
    ]
