# Generated by Django 6.0.2 on 2026-02-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaceAcademyApp', '0014_pacs_unique_pac_students_unique_students'),
        ('PaceAcademyApp', '0015_remove_pacs_unique_email_pacs_and_more'),
    ]

    operations = [
    ]
